### ISSUE TITLE
Full-scale tests failing - simulation solution doesn't match analytical solution

### ISSUE THREAD

**Issue by baagaard-usgs** [geodynamics/pylith#260]
@knepley The libtests and mmstests are passing, but several full-scale tests are failing. They run without crashing, but the computed solution no longer matches the analytical solution. It isn't clear to me what changes you made might be causing the problem.

# Reproduce

PETSc branch: **knepley/pylith**
PyLith branch: **baagaard/update-boundary-integration-dm-set-aux-vec** (cleaned up with forced push)

```
make install
make check -C libtests # should pass
make check -C mmstests # should pass
make check -C fullscale/cornercases/2d
```

# Error

```
test_bcdirichlet_info (TestAxialDispOneCell.TestQuad) ... ok
test_bcdirichlet_solution (TestAxialDispOneCell.TestQuad) ... ok
test_domain_solution (TestAxialDispOneCell.TestQuad) ... FAIL
test_material_info (TestAxialDispOneCell.TestQuad) ... ok
test_material_solution (TestAxialDispOneCell.TestQuad) ... FAIL
test_bcdirichlet_info (TestAxialDispConstrained.TestTri) ... ok
test_bcdirichlet_solution (TestAxialDispConstrained.TestTri) ... ok
test_domain_solution (TestAxialDispConstrained.TestTri) ... ok
test_material_info (TestAxialDispConstrained.TestTri) ... ok
test_material_solution (TestAxialDispConstrained.TestTri) ... ok
test_bcdirichlet_info (TestAxialDispConstrained.TestQuad) ... ok
test_bcdirichlet_solution (TestAxialDispConstrained.TestQuad) ... ok
test_domain_solution (TestAxialDispConstrained.TestQuad) ... ok
test_material_info (TestAxialDispConstrained.TestQuad) ... ok
test_material_solution (TestAxialDispConstrained.TestQuad) ... ok

======================================================================
FAIL: test_domain_solution (TestAxialDispOneCell.TestQuad)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/baagaard/src/cig/pylith/tests/fullscale/cornercases/2d/TestAxialDispOneCell.py", line 54, in test_domain_solution
    check_data(filename, self, self.DOMAIN, vertexFields=vertexFields)
  File "/Users/baagaard/tools/unix/pylith-develop/clang-3.6.0-py38/lib/python3.8/site-packages/pylith/tests/FullTestApp.py", line 268, in check_data
    checker.checkVertexField(field)
  File "/Users/baagaard/tools/unix/pylith-develop/clang-3.6.0-py38/lib/python3.8/site-packages/pylith/tests/FullTestApp.py", line 167, in checkVertexField
    self._checkField(fieldName, fieldE, field, vertices, mask)
  File "/Users/baagaard/tools/unix/pylith-develop/clang-3.6.0-py38/lib/python3.8/site-packages/pylith/tests/FullTestApp.py", line 245, in _checkField
    self.testcase.assertEqual(npts, numpy.sum(okay))
AssertionError: 4 != 2

======================================================================
FAIL: test_material_solution (TestAxialDispOneCell.TestQuad)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/baagaard/src/cig/pylith/tests/fullscale/cornercases/2d/TestAxialDispOneCell.py", line 69, in test_material_solution
    check_data(filename, self,
  File "/Users/baagaard/tools/unix/pylith-develop/clang-3.6.0-py38/lib/python3.8/site-packages/pylith/tests/FullTestApp.py", line 268, in check_data
    checker.checkVertexField(field)
  File "/Users/baagaard/tools/unix/pylith-develop/clang-3.6.0-py38/lib/python3.8/site-packages/pylith/tests/FullTestApp.py", line 167, in checkVertexField
    self._checkField(fieldName, fieldE, field, vertices, mask)
  File "/Users/baagaard/tools/unix/pylith-develop/clang-3.6.0-py38/lib/python3.8/site-packages/pylith/tests/FullTestApp.py", line 245, in _checkField
    self.testcase.assertEqual(npts, numpy.sum(okay))
AssertionError: 4 != 2

----------------------------------------------------------------------
Ran 15 tests in 11.141s

FAILED (failures=2)
Error in component 0 of field 'displacement' at time step 0.
Total # not okay: 2
Ratio (maskR), # not okay: 2
Expected values (not okay): [0.32748538 0.32748538]
Computed values (not okay): [-0.29945764 -0.29945764]
Ratio (not okay): [1.91441528 1.91441528]
Ratio Coordinates (not okay): [[ 4000. -4000.]
 [ 4000.  4000.]]
Tolerance Absolute Mask: 0.1
Ratio Tolerance: 1e-05
Error in component 0 of field 'displacement' at time step 0.
Total # not okay: 2
Ratio (maskR), # not okay: 2
Expected values (not okay): [0.32748538 0.32748538]
Computed values (not okay): [-0.29945764 -0.29945764]
Ratio (not okay): [1.91441528 1.91441528]
Ratio Coordinates (not okay): [[ 4000. -4000.]
 [ 4000.  4000.]]
Tolerance Absolute Mask: 0.1
Ratio Tolerance: 1e-05
FAIL test_pylith.py (exit status: 1)
```

**Comment by knepley** [comment]
@baagaard It is most likely something with boundary condition specification. I think the first thing to do is print out the DS and make sure all the kernels are correct.

**Comment by baagaard-usgs** [comment]
@knepley Will dig deeper. I am puzzled why some tests pass but others don't. The PETSc integration seems exceedingly fragile right now.

**Comment by knepley** [comment]
Not sure. All the PETSc tests pass. I am not sure where the fragility is.

**Comment by baagaard-usgs** [comment]
@knepley The solution DS shows INVALID for a boundary condition. It also shows only one boundary condition, when I have two. With the current knepley/pylith branch, how are we supposed to be 
1. Adding boundaries using `PetscDSAddBoundary()`.
2. Using `DMPlexInsertBoundaryValuesEssentialBdField()`

These calls are in `ConstraintSpatialDB.cc`

`PetscDSView` on the solution shows

```
Discrete System with 1 fields
    cell total dim 8 total comp 2
  Field displacement FEM2 components (implicit) (Nq 4 Nqc 1) 1-jet
    PetscFE Object: displacement 1 MPI processes
      type: basic
      Basic Finite Element in 2 dimensions with 2 components
      PetscSpace Object: displacement 1 MPI processes
        type: poly
        Space in 2 variables with 2 components, size 8
        Tensor polynomial space of degree 1
      PetscDualSpace Object: displacement 1 MPI processes
        type: lagrange
        Dual space with 2 components, size 8
        Continuous tensor Lagrange dual space
        Quadrature of order 3 on 4 points (dim 2)
    Boundary boundary_xneg (boundary_xneg) INVALID
      components: 0, 1
      values: 1
    Weak Form System with 1 fields
  Weak Form System with 1 fields
```

**Comment by baagaard-usgs** [comment]
@knepley I don't see any of your tests using `DM_BC_ESSENTIAL_BD_FIELD`. The MMS tests are passing which use analytical functions (`DM_BC_ESSENTIAL`), so I think the problem is the normal use case in PyLith with a boundary field + pointwise function. I don't know how to make further progress without your help.

**Comment by knepley** [comment]
Okay, I fixed, DM_BC_ESSENTIAL_BD)FIELD printing. I will put it in another MR. The only problem was the name.

The PetscDSAddBoundary() is only being called once, not twice. If you have to BC, why is it only being called once?

`:/PETSc3/cig/pylith-cpetsc/tests/fullscale/cornercases/2d$ PETSC_OPTIONS="-malloc_debug 0 -dm_petscds_view" nemesis TestAxialDispOneCell.py
test_bcdirichlet_info (__main__.TestQuad) ... Discrete System with 1 fields
    cell total dim 8 total comp 2
  Field displacement FEM2 components (implicit) (Nq 4 Nqc 1) 1-jet
    PetscFE Object: displacement 1 MPI processes
      type: basic
      Basic Finite Element in 2 dimensions with 2 components
      PetscSpace Object: displacement 1 MPI processes
        type: poly
        Space in 2 variables with 2 components, size 8
        Tensor polynomial space of degree 1
      PetscDualSpace Object: displacement 1 MPI processes
        type: lagrange
        Dual space with 2 components, size 8
        Continuous tensor Lagrange dual space
        Quadrature of order 3 on 4 points (dim 2)
    Boundary boundary_xneg (boundary_xneg) ESSENTIAL_BD_FIELD
      components: 0, 1
      values: 1
      func: _ZN6pylith9fekernels15TimeDependentFn14initial_vectorEiiiPKiS3_PKdS5_S5_S3_S3_S5_S5_S5_dS5_S5_iS5_Pd
    Weak Form System with 1 fields
  Weak Form System with 1 fields
ok
test_bcdirichlet_solution (__main__.TestQuad) ... ok
test_domain_solution (__main__.TestQuad) ... Error in component 0 of field 'displacement' at time step 0.
`

**Comment by baagaard-usgs** [comment]
@knepley Correction: I have one Dirichlet BC and one Neumann BC. The fully constrained case passes, so the problem must be in the Neumann BC. I believe you said something about the DS must be with the boundary DM. Are we still missing something in the residual setup for [`IntegratorBoundary::-computeResidual()`](https://github.com/geodynamics/pylith/blob/baagaard/update-boundary-integration-dm-set-aux-vec/libsrc/pylith/feassemble/IntegratorBoundary.cc#L320)?

**Comment by knepley** [comment]
Shoot, I should have thought of that. Yes, I had to change those in all the PETSc source. I should have changed them all in PyLith. Maybe we need a better system so that I make those systemic changes at the same time in PyLith. We used to have this problem all the time in petsc4py, but then we integrated it. We still have it in SLEPc.

**Comment by knepley** [comment]
Okay, I have looked. We were not managing the Neumann conditions through PETSc. I think PyLith wanted to manage that part internally. That means that PyLith must call ComputeBdResidual* itself. Looking now...

**Comment by knepley** [comment]
Okay, the Neumann kernel had the wrong key (no label or value). I fixed this and pushed to baagaard/update-boundary-integrate-dm-set-aux-vec . Now I get
```
Assertion failed: (_numA == numA), function g0_initial_vector, file ../../../pylith-git/libsrc/pylith/fekernels/NeumannTimeDependent.cc, line 93.
```
which seems to indicate that the kernel is expecting a different auxiliary field

**Comment by baagaard-usgs** [comment]
@knepley This pointwise function setup is a mess! I can get the boundary integration to work if I set the auxiliary field vector using label=NULL, labelValue=0. It looks like whenever you are pulling out the auxiliary vec you use `DMGetAuxiliaryVec(dm, NULL, 0)`.

## Consistent use of label/labelValue but wrong result

Why is this not the correct code?

```
    err = DMSetAuxiliaryVec(dmSoln, dmLabel, labelValue, auxiliaryField->localVector());PYLITH_CHECK_ERROR(err);

    for (size_t i = 0; i < kernels.size(); ++i) {
        PetscWeakForm wf;
        const PetscInt i_field = solution.subfieldInfo(kernels[i].subfield.c_str()).index;
        err = PetscDSGetWeakForm(prob, &wf);PYLITH_CHECK_ERROR(err);
        err = PetscWeakFormSetIndexBdResidual(wf, dmLabel, labelValue, i_field, 0, kernels[i].r0, 0, kernels[i].r1);PYLITH_CHECK_ERROR(err);
        err = DMPlexComputeBdResidualSingle(dmSoln, t, wf, dmLabel, 1, &labelValue, i_field, solution.localVector(), solutionDot.localVector(), residual->localVector());PYLITH_CHECK_ERROR(err);
    } // for
```

## Inconsistent use of label/labelValue but correct result

```
    err = DMSetAuxiliaryVec(dmSoln, NULL, 0, auxiliaryField->localVector());PYLITH_CHECK_ERROR(err);

    for (size_t i = 0; i < kernels.size(); ++i) {
        PetscWeakForm wf;
        const PetscInt i_field = solution.subfieldInfo(kernels[i].subfield.c_str()).index;
        err = PetscDSGetWeakForm(prob, &wf);PYLITH_CHECK_ERROR(err);
        err = PetscWeakFormSetIndexBdResidual(wf, dmLabel, labelValue, i_field, 0, kernels[i].r0, 0, kernels[i].r1);PYLITH_CHECK_ERROR(err);
        err = DMPlexComputeBdResidualSingle(dmSoln, t, wf, dmLabel, 1, &labelValue, i_field, solution.localVector(), solutionDot.localVector(), residual->localVector());PYLITH_CHECK_ERROR(err);
    } // for
```

**Comment by knepley** [comment]
Yes, I was trying to change things in stages so that everything did not break at once. However, it looks like things broke anyway. The idea was to set all AuxVec to (NULL, 0) to start and get everything working. This should always work since we could not have required more than one Aux before.

Now I will make an MR that changes AuxVec to (label, val), make sure PETSc passes, change all occurences in PyLith, and run make sure everything passes. I will do my best to get it done before the meeting.

**Comment by baagaard-usgs** [comment]
@knepley We will be able to isolate these bugs quicker once I get more of the C++ unit tests implemented. It would have been clear that the boundary integration was failing.

When we add thee features, It would help if you could be more precise about exactly what is implemented and what needs updating. Pointing to corresponding examples in PETSc would help.

**Comment by knepley** [comment]
@baagaard Yes I agree. When I do the next MR, I will post on the PyLith Slack and give a summary of the updates. That should be the practice for PyLith MRs in PETSc.
